apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:                   # 2 spaces indentation for spec fields
  - default:                # Max limit, 4 spaces indentation for lists and nested fields
      cpu: "1"              # 6 spaces for nested fields under default
    defaultRequest:         # Min request
      cpu: "0.5"
    type: Container         # 4 spaces indentation for type under the list item