apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: myjob
spec:
  schedule: "* * * * *"                      # Every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mycont
            image: ubuntu
            command: ["/bin/bash", "-c", "echo Saidemy; sleep 10"]
          restartPolicy: Never                     # Terminated pod won't get started again. New pod gets created in place of it.
