apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max-demo-lr
spec:
  limits:
  - max:                           # Max Limit
      memory: "1Gi"                # Gibi bytes
    min:                           # Min Request
      memory: "500Mi"              # Mebibytes
    type: Container