apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myebsvolclaim
spec:
  accessModes:
    - ReadWriteOnce                         # I want a volume which will have read & write access
  resources:
    requests:
      storage: 1Gi                          # I want a volume having 1Gi (Claiming) for my pod from any available PV objects


apiVersion: v1
kind: PersistentVolume
metadata:
  name: myebsvol
spec:
  capacity:
    storage: 1Gi                            # Out of 20 GB, you want only 1GB as PV object
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: <MY-EBS-VOLUME-ID>            # Replace with your actual EBS volume ID
    fsType: ext4


apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebspvdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypv
  template:
    metadata:
      labels:
        app: mypv
    spec:
      containers:
      - name: c01
        image: centos
        command: ["/bin/bash", "-c", "sleep 10000"]
        volumeMounts:
        - name: myvolume
          mountPath: "/tmp/contvol"                  # this directory will be created inside the container
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: myebsvolclaim                   # PV Claim that we created earlier